name: Lint Code
 
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
 
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
 
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
 
      # Install dependencies
      - name: Install dependencies
        run: npm install
        
      - name: Install dependencies1
        run: npm install eslint   
   
      # Run linter
      - name: Run ESLint
        run: npm run lint
