name: Deploy to AWS S3
 
on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
 
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      # Sync files to the S3 bucket
      - name: Sync Files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete
